language: node_js
node_js:
  - "node"
  - "8"
cache:
  directories:
    - "node_modules"
services: 
  - postgresql
  - redis-server
before_script:
  - psql -c 'CREATE DATABASE stellar_testing;' -U postgres