language: node_js
node_js:
- node
- 9.4.0
cache:
  directories:
  - node_modules
services:
- postgresql
- redis-server
- docker
before_script:
- psql -c 'CREATE DATABASE stellar_testing;' -U postgres
after_success:
- "./build_and_deploy.sh"
