version: '3'
services:
  app:
    #Note: No ports are defined in this default file, as docker-compose files concatenate instead of override array values.
    #Port mappings are therefore relegated to the branch specific docker-compose files
    image: davidbulnes/stellar-bot:latest
    build:
      . # build using the Dockerfile from the root directory of the repo
    volumes:
      # make our .env file available inside the container. We need an absolute path (using pwd) because it is a single file volume.
      - ${PWD}/.env:/usr/src/app/.env
    working_dir: /usr/src/app
    #stdin_open: true # necessary for a shell session inside the container
    #tty: true # shell session
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    # Encapsulate the command with bash -c so we can add additional steps easily.
    # Wait for the db connection before starting the app
    command: bash -c "./wait_for_postgres.sh npm run app"
    #environment:
    #  - PG_URL=postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB}
  db:
    image: postgres:10.1
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      #- POSTGRES_DATABASE=${PG_DB}
  redis:
    image: redis:3.2.11
    volumes:
      - ./redisdb:/data
    