version: '3'
services:
  app:
    image: davidbulnes/stellar-bot:${STELLARBOT_MASTER_TAG}
    ports:
      - 5000:5000
    environment:
     - TAG=${STELLARBOT_MASTER_TAG}
  db:
    ports:
      - 5455:5432
  redis:
    ports:
      - 6379:6379